<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>

<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_NumPy_logo.png' width=200 align='left'><br/>

## Table of Contents

* [1 Element-Wise Operations](#1-Element-Wise-Operations)
* [2 Linear Algebra](#2-Linear-Algebra)
* [3 Array Statistics](#3-Array-Statistics)

In [1]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations. 

In [2]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.2149188  0.64590775 0.86148976 0.49575744]
 [0.972641   0.22979073 0.96347519 0.01196942]
 [0.12373972 0.12883367 0.59346235 0.6243384 ]
 [0.35016111 0.91817003 0.77496698 0.37324691]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.96154488 0.43045822 0.08928856 0.12327609]
 [0.43158741 0.38805724 0.95522785 0.97924729]
 [0.8780902  0.93306844 0.4976354  0.32937219]
 [0.27092181 0.64438281 0.02677429 0.75702875]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [3]:
a + 5 # Element wise scalar addition.

array([[5.2149188 , 5.64590775, 5.86148976, 5.49575744],
       [5.972641  , 5.22979073, 5.96347519, 5.01196942],
       [5.12373972, 5.12883367, 5.59346235, 5.6243384 ],
       [5.35016111, 5.91817003, 5.77496698, 5.37324691]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [4]:
a - 5 # Element wise scalar subtraction.

array([[-4.7850812 , -4.35409225, -4.13851024, -4.50424256],
       [-4.027359  , -4.77020927, -4.03652481, -4.98803058],
       [-4.87626028, -4.87116633, -4.40653765, -4.3756616 ],
       [-4.64983889, -4.08182997, -4.22503302, -4.62675309]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [5]:
a * 10 # Element wise scalar multiplication.

array([[2.14918796, 6.45907753, 8.61489756, 4.95757437],
       [9.72641002, 2.29790731, 9.6347519 , 0.1196942 ],
       [1.23739724, 1.28833674, 5.93462351, 6.24338404],
       [3.50161109, 9.18170028, 7.74966978, 3.73246913]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [6]:
a/10 # Element wise scalar division.

array([[0.02149188, 0.06459078, 0.08614898, 0.04957574],
       [0.0972641 , 0.02297907, 0.09634752, 0.00119694],
       [0.01237397, 0.01288337, 0.05934624, 0.06243384],
       [0.03501611, 0.091817  , 0.0774967 , 0.03732469]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [7]:
a + b # Element wise array/vector addition.

array([[1.17646368, 1.07636597, 0.95077832, 0.61903352],
       [1.40422841, 0.61784797, 1.91870304, 0.99121671],
       [1.00182992, 1.06190212, 1.09109775, 0.9537106 ],
       [0.62108292, 1.56255284, 0.80174127, 1.13027567]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [8]:
a - b # Element wise array/vector subtraction.

array([[-0.74662609,  0.21544953,  0.77220119,  0.37248135],
       [ 0.54105359, -0.15826651,  0.00824734, -0.96727787],
       [-0.75435048, -0.80423477,  0.09582695,  0.29496621],
       [ 0.0792393 ,  0.27378722,  0.74819269, -0.38378184]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [9]:
a * b # Element wise array/vector multiplication.

array([[0.20665407, 0.2780363 , 0.07692118, 0.06111504],
       [0.41977961, 0.08917196, 0.92033834, 0.01172102],
       [0.10865464, 0.12021064, 0.29532787, 0.20563971],
       [0.09486628, 0.59165298, 0.02074919, 0.28255865]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [10]:
a / b # element wise array/vector division

array([[2.23514055e-01, 1.50051207e+00, 9.64837732e+00, 4.02152153e+00],
       [2.25363618e+00, 5.92156791e-01, 1.00863389e+00, 1.22230824e-02],
       [1.40919150e-01, 1.38075266e-01, 1.19256459e+00, 1.89554071e+00],
       [1.29248031e+00, 1.42488287e+00, 2.89444457e+01, 4.93041924e-01]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [11]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.2149188  0.64590775 0.86148976 0.49575744]
 [0.972641   0.22979073 0.96347519 0.01196942]
 [0.12373972 0.12883367 0.59346235 0.6243384 ]
 [0.35016111 0.91817003 0.77496698 0.37324691]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.10850851 0.55383723 0.56583753 0.3462489 ]
 [0.35362981 0.86668629 0.58165498 0.39833055]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "<ipython-input-11-db3a8552b781>", line 10, in <module>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)` 

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array. 

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1
 
The examples below show how `B` is successfully broadcasted to `A` according to the rules above.
 
``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = np.matmul(a,b) 

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be 
                                                          # same for matrix multiplication

### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b 
array_info(c)

### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=matrix%20inverse" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot%20product" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b) 
array_info(dot_prod)

## 3 Array Statistics

### 3.1 Sum

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

### 3.2 Sum Along Axis

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

### 3.3 Minimum and Maximum

In [ ]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

### 3.4 Min and Max along Axis

In [ ]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

### 3.5 Mean and Standard Deviation

In [ ]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [ ]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))  
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))   